Show message headers in the log
umbrellio/rabbit_messaging pull request #7
Opened 2021-03-04 08:09 UTC by artyom-ukhabin

2021-03-04 08:13 UTC, artyom-ukhabin commented on lib/rabbit/publishing.rb
> +        message.real_exchange_name, message.routing_key, message.headers,
Maybe I should make them optional? Or explicit `key / {} / event` is better?

2021-03-04 08:25 UTC, artyom-ukhabin commented on lib/rabbit/publishing.rb
> +        message.real_exchange_name, message.routing_key, message.headers,
Maybe I should make them optional? Or explicit key / {} / event is better?

2021-03-04 08:37 UTC, VegetableProphet approved these changes

2021-03-04 10:40 UTC, tycooon commented on lib/rabbit/publishing.rb
>        headers = [
Мб это переименуем в metadata? А то получается хедеры внутри хедеров 🤔

2021-03-04 10:40 UTC, tycooon commented on lib/rabbit/publishing.rb
> +        message.real_exchange_name, message.routing_key, message.headers,
Лучше явно имхо.

2021-03-04 14:31 UTC, tycooon requested changes
Тесты падают, давай перепилим на гитхаб экшены? Я вот тут делал например https://github.com/umbrellio/table_sync/pull/54

2021-03-04 16:57 UTC, 0exp approved these changes

2021-03-04 16:57 UTC, 0exp commented on CHANGELOG.md
> +## [0.9.1] - 2021-03-04
это уже минорное обновление. не патч

2021-03-04 16:58 UTC, 0exp commented on CHANGELOG.md
> +## [0.9.1] - 2021-03-04
и дату релиза видимо надо будет подправить тоже теперь :)

2021-03-05 13:43 UTC, tycooon approved these changes

2021-03-05 13:43 UTC, merged